name: Build and Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./01_Simple_CI_Project/01_Simple_CI_Project.csproj

    - name: Build
      run: dotnet build ./01_Simple_CI_Project/01_Simple_CI_Project.csproj --no-restore

    - name: Run
      run: dotnet run --project ./01_Simple_CI_Project/01_Simple_CI_Project.csproj